gdjs.BRIDGECode = {};
gdjs.BRIDGECode.localVariables = [];
gdjs.BRIDGECode.GDBRIDGE_9595PART_95951Objects1= [];
gdjs.BRIDGECode.GDBRIDGE_9595PART_95951Objects2= [];
gdjs.BRIDGECode.GDjointObjects1= [];
gdjs.BRIDGECode.GDjointObjects2= [];
gdjs.BRIDGECode.GDNewSpriteObjects1= [];
gdjs.BRIDGECode.GDNewSpriteObjects2= [];
gdjs.BRIDGECode.GDrevoluteObjects1= [];
gdjs.BRIDGECode.GDrevoluteObjects2= [];
gdjs.BRIDGECode.GDNewSprite2Objects1= [];
gdjs.BRIDGECode.GDNewSprite2Objects2= [];
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95951Objects1= [];
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95951Objects2= [];
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95952Objects1= [];
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95952Objects2= [];
gdjs.BRIDGECode.GDPAUSE_95951Objects1= [];
gdjs.BRIDGECode.GDPAUSE_95951Objects2= [];
gdjs.BRIDGECode.GDPAUSE_95952Objects1= [];
gdjs.BRIDGECode.GDPAUSE_95952Objects2= [];
gdjs.BRIDGECode.GDBLACK_9595OVERLAYObjects1= [];
gdjs.BRIDGECode.GDBLACK_9595OVERLAYObjects2= [];
gdjs.BRIDGECode.GDMMENUObjects1= [];
gdjs.BRIDGECode.GDMMENUObjects2= [];
gdjs.BRIDGECode.GDQUITObjects1= [];
gdjs.BRIDGECode.GDQUITObjects2= [];
gdjs.BRIDGECode.GDSETTINGSObjects1= [];
gdjs.BRIDGECode.GDSETTINGSObjects2= [];
gdjs.BRIDGECode.GDPAUSE_95953Objects1= [];
gdjs.BRIDGECode.GDPAUSE_95953Objects2= [];
gdjs.BRIDGECode.GDPAUSE_95954Objects1= [];
gdjs.BRIDGECode.GDPAUSE_95954Objects2= [];
gdjs.BRIDGECode.GDBLACK_9595OVERLAY2Objects1= [];
gdjs.BRIDGECode.GDBLACK_9595OVERLAY2Objects2= [];
gdjs.BRIDGECode.GDYESObjects1= [];
gdjs.BRIDGECode.GDYESObjects2= [];
gdjs.BRIDGECode.GDNOObjects1= [];
gdjs.BRIDGECode.GDNOObjects2= [];
gdjs.BRIDGECode.GDSURE_9595Objects1= [];
gdjs.BRIDGECode.GDSURE_9595Objects2= [];
gdjs.BRIDGECode.GDBACKBTNObjects1= [];
gdjs.BRIDGECode.GDBACKBTNObjects2= [];
gdjs.BRIDGECode.GDHAMBURGERObjects1= [];
gdjs.BRIDGECode.GDHAMBURGERObjects2= [];
gdjs.BRIDGECode.GDMUSICSLIDERObjects1= [];
gdjs.BRIDGECode.GDMUSICSLIDERObjects2= [];
gdjs.BRIDGECode.GDSFXSLIDERObjects1= [];
gdjs.BRIDGECode.GDSFXSLIDERObjects2= [];
gdjs.BRIDGECode.GDPAUSBACKObjects1= [];
gdjs.BRIDGECode.GDPAUSBACKObjects2= [];
gdjs.BRIDGECode.GDPAUSBACK2Objects1= [];
gdjs.BRIDGECode.GDPAUSBACK2Objects2= [];
gdjs.BRIDGECode.GDVOLSLIDEObjects1= [];
gdjs.BRIDGECode.GDVOLSLIDEObjects2= [];
gdjs.BRIDGECode.GDVOLBUTTONObjects1= [];
gdjs.BRIDGECode.GDVOLBUTTONObjects2= [];
gdjs.BRIDGECode.GDVOLTEXTObjects1= [];
gdjs.BRIDGECode.GDVOLTEXTObjects2= [];
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95953Objects1= [];
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95953Objects2= [];
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95954Objects1= [];
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95954Objects2= [];
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95955Objects1= [];
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95955Objects2= [];
gdjs.BRIDGECode.GDPHONEObjects1= [];
gdjs.BRIDGECode.GDPHONEObjects2= [];
gdjs.BRIDGECode.GDPAT_9595HEADObjects1= [];
gdjs.BRIDGECode.GDPAT_9595HEADObjects2= [];
gdjs.BRIDGECode.GDPAT_9595BGObjects1= [];
gdjs.BRIDGECode.GDPAT_9595BGObjects2= [];
gdjs.BRIDGECode.GDPATALKObjects1= [];
gdjs.BRIDGECode.GDPATALKObjects2= [];
gdjs.BRIDGECode.GDPATALK2Objects1= [];
gdjs.BRIDGECode.GDPATALK2Objects2= [];


gdjs.BRIDGECode.eventsList0 = function(runtimeScene) {

{


let isConditionTrue_0 = false;
{
}

}


};

gdjs.BRIDGECode.func = function(runtimeScene) {
runtimeScene.getOnceTriggers().startNewFrame();

gdjs.BRIDGECode.GDBRIDGE_9595PART_95951Objects1.length = 0;
gdjs.BRIDGECode.GDBRIDGE_9595PART_95951Objects2.length = 0;
gdjs.BRIDGECode.GDjointObjects1.length = 0;
gdjs.BRIDGECode.GDjointObjects2.length = 0;
gdjs.BRIDGECode.GDNewSpriteObjects1.length = 0;
gdjs.BRIDGECode.GDNewSpriteObjects2.length = 0;
gdjs.BRIDGECode.GDrevoluteObjects1.length = 0;
gdjs.BRIDGECode.GDrevoluteObjects2.length = 0;
gdjs.BRIDGECode.GDNewSprite2Objects1.length = 0;
gdjs.BRIDGECode.GDNewSprite2Objects2.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95951Objects1.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95951Objects2.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95952Objects1.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95952Objects2.length = 0;
gdjs.BRIDGECode.GDPAUSE_95951Objects1.length = 0;
gdjs.BRIDGECode.GDPAUSE_95951Objects2.length = 0;
gdjs.BRIDGECode.GDPAUSE_95952Objects1.length = 0;
gdjs.BRIDGECode.GDPAUSE_95952Objects2.length = 0;
gdjs.BRIDGECode.GDBLACK_9595OVERLAYObjects1.length = 0;
gdjs.BRIDGECode.GDBLACK_9595OVERLAYObjects2.length = 0;
gdjs.BRIDGECode.GDMMENUObjects1.length = 0;
gdjs.BRIDGECode.GDMMENUObjects2.length = 0;
gdjs.BRIDGECode.GDQUITObjects1.length = 0;
gdjs.BRIDGECode.GDQUITObjects2.length = 0;
gdjs.BRIDGECode.GDSETTINGSObjects1.length = 0;
gdjs.BRIDGECode.GDSETTINGSObjects2.length = 0;
gdjs.BRIDGECode.GDPAUSE_95953Objects1.length = 0;
gdjs.BRIDGECode.GDPAUSE_95953Objects2.length = 0;
gdjs.BRIDGECode.GDPAUSE_95954Objects1.length = 0;
gdjs.BRIDGECode.GDPAUSE_95954Objects2.length = 0;
gdjs.BRIDGECode.GDBLACK_9595OVERLAY2Objects1.length = 0;
gdjs.BRIDGECode.GDBLACK_9595OVERLAY2Objects2.length = 0;
gdjs.BRIDGECode.GDYESObjects1.length = 0;
gdjs.BRIDGECode.GDYESObjects2.length = 0;
gdjs.BRIDGECode.GDNOObjects1.length = 0;
gdjs.BRIDGECode.GDNOObjects2.length = 0;
gdjs.BRIDGECode.GDSURE_9595Objects1.length = 0;
gdjs.BRIDGECode.GDSURE_9595Objects2.length = 0;
gdjs.BRIDGECode.GDBACKBTNObjects1.length = 0;
gdjs.BRIDGECode.GDBACKBTNObjects2.length = 0;
gdjs.BRIDGECode.GDHAMBURGERObjects1.length = 0;
gdjs.BRIDGECode.GDHAMBURGERObjects2.length = 0;
gdjs.BRIDGECode.GDMUSICSLIDERObjects1.length = 0;
gdjs.BRIDGECode.GDMUSICSLIDERObjects2.length = 0;
gdjs.BRIDGECode.GDSFXSLIDERObjects1.length = 0;
gdjs.BRIDGECode.GDSFXSLIDERObjects2.length = 0;
gdjs.BRIDGECode.GDPAUSBACKObjects1.length = 0;
gdjs.BRIDGECode.GDPAUSBACKObjects2.length = 0;
gdjs.BRIDGECode.GDPAUSBACK2Objects1.length = 0;
gdjs.BRIDGECode.GDPAUSBACK2Objects2.length = 0;
gdjs.BRIDGECode.GDVOLSLIDEObjects1.length = 0;
gdjs.BRIDGECode.GDVOLSLIDEObjects2.length = 0;
gdjs.BRIDGECode.GDVOLBUTTONObjects1.length = 0;
gdjs.BRIDGECode.GDVOLBUTTONObjects2.length = 0;
gdjs.BRIDGECode.GDVOLTEXTObjects1.length = 0;
gdjs.BRIDGECode.GDVOLTEXTObjects2.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95953Objects1.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95953Objects2.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95954Objects1.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95954Objects2.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95955Objects1.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95955Objects2.length = 0;
gdjs.BRIDGECode.GDPHONEObjects1.length = 0;
gdjs.BRIDGECode.GDPHONEObjects2.length = 0;
gdjs.BRIDGECode.GDPAT_9595HEADObjects1.length = 0;
gdjs.BRIDGECode.GDPAT_9595HEADObjects2.length = 0;
gdjs.BRIDGECode.GDPAT_9595BGObjects1.length = 0;
gdjs.BRIDGECode.GDPAT_9595BGObjects2.length = 0;
gdjs.BRIDGECode.GDPATALKObjects1.length = 0;
gdjs.BRIDGECode.GDPATALKObjects2.length = 0;
gdjs.BRIDGECode.GDPATALK2Objects1.length = 0;
gdjs.BRIDGECode.GDPATALK2Objects2.length = 0;

gdjs.BRIDGECode.eventsList0(runtimeScene);
gdjs.BRIDGECode.GDBRIDGE_9595PART_95951Objects1.length = 0;
gdjs.BRIDGECode.GDBRIDGE_9595PART_95951Objects2.length = 0;
gdjs.BRIDGECode.GDjointObjects1.length = 0;
gdjs.BRIDGECode.GDjointObjects2.length = 0;
gdjs.BRIDGECode.GDNewSpriteObjects1.length = 0;
gdjs.BRIDGECode.GDNewSpriteObjects2.length = 0;
gdjs.BRIDGECode.GDrevoluteObjects1.length = 0;
gdjs.BRIDGECode.GDrevoluteObjects2.length = 0;
gdjs.BRIDGECode.GDNewSprite2Objects1.length = 0;
gdjs.BRIDGECode.GDNewSprite2Objects2.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95951Objects1.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95951Objects2.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95952Objects1.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95952Objects2.length = 0;
gdjs.BRIDGECode.GDPAUSE_95951Objects1.length = 0;
gdjs.BRIDGECode.GDPAUSE_95951Objects2.length = 0;
gdjs.BRIDGECode.GDPAUSE_95952Objects1.length = 0;
gdjs.BRIDGECode.GDPAUSE_95952Objects2.length = 0;
gdjs.BRIDGECode.GDBLACK_9595OVERLAYObjects1.length = 0;
gdjs.BRIDGECode.GDBLACK_9595OVERLAYObjects2.length = 0;
gdjs.BRIDGECode.GDMMENUObjects1.length = 0;
gdjs.BRIDGECode.GDMMENUObjects2.length = 0;
gdjs.BRIDGECode.GDQUITObjects1.length = 0;
gdjs.BRIDGECode.GDQUITObjects2.length = 0;
gdjs.BRIDGECode.GDSETTINGSObjects1.length = 0;
gdjs.BRIDGECode.GDSETTINGSObjects2.length = 0;
gdjs.BRIDGECode.GDPAUSE_95953Objects1.length = 0;
gdjs.BRIDGECode.GDPAUSE_95953Objects2.length = 0;
gdjs.BRIDGECode.GDPAUSE_95954Objects1.length = 0;
gdjs.BRIDGECode.GDPAUSE_95954Objects2.length = 0;
gdjs.BRIDGECode.GDBLACK_9595OVERLAY2Objects1.length = 0;
gdjs.BRIDGECode.GDBLACK_9595OVERLAY2Objects2.length = 0;
gdjs.BRIDGECode.GDYESObjects1.length = 0;
gdjs.BRIDGECode.GDYESObjects2.length = 0;
gdjs.BRIDGECode.GDNOObjects1.length = 0;
gdjs.BRIDGECode.GDNOObjects2.length = 0;
gdjs.BRIDGECode.GDSURE_9595Objects1.length = 0;
gdjs.BRIDGECode.GDSURE_9595Objects2.length = 0;
gdjs.BRIDGECode.GDBACKBTNObjects1.length = 0;
gdjs.BRIDGECode.GDBACKBTNObjects2.length = 0;
gdjs.BRIDGECode.GDHAMBURGERObjects1.length = 0;
gdjs.BRIDGECode.GDHAMBURGERObjects2.length = 0;
gdjs.BRIDGECode.GDMUSICSLIDERObjects1.length = 0;
gdjs.BRIDGECode.GDMUSICSLIDERObjects2.length = 0;
gdjs.BRIDGECode.GDSFXSLIDERObjects1.length = 0;
gdjs.BRIDGECode.GDSFXSLIDERObjects2.length = 0;
gdjs.BRIDGECode.GDPAUSBACKObjects1.length = 0;
gdjs.BRIDGECode.GDPAUSBACKObjects2.length = 0;
gdjs.BRIDGECode.GDPAUSBACK2Objects1.length = 0;
gdjs.BRIDGECode.GDPAUSBACK2Objects2.length = 0;
gdjs.BRIDGECode.GDVOLSLIDEObjects1.length = 0;
gdjs.BRIDGECode.GDVOLSLIDEObjects2.length = 0;
gdjs.BRIDGECode.GDVOLBUTTONObjects1.length = 0;
gdjs.BRIDGECode.GDVOLBUTTONObjects2.length = 0;
gdjs.BRIDGECode.GDVOLTEXTObjects1.length = 0;
gdjs.BRIDGECode.GDVOLTEXTObjects2.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95953Objects1.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95953Objects2.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95954Objects1.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95954Objects2.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95955Objects1.length = 0;
gdjs.BRIDGECode.GDELEC_9595PORTAL_9595PART_95955Objects2.length = 0;
gdjs.BRIDGECode.GDPHONEObjects1.length = 0;
gdjs.BRIDGECode.GDPHONEObjects2.length = 0;
gdjs.BRIDGECode.GDPAT_9595HEADObjects1.length = 0;
gdjs.BRIDGECode.GDPAT_9595HEADObjects2.length = 0;
gdjs.BRIDGECode.GDPAT_9595BGObjects1.length = 0;
gdjs.BRIDGECode.GDPAT_9595BGObjects2.length = 0;
gdjs.BRIDGECode.GDPATALKObjects1.length = 0;
gdjs.BRIDGECode.GDPATALKObjects2.length = 0;
gdjs.BRIDGECode.GDPATALK2Objects1.length = 0;
gdjs.BRIDGECode.GDPATALK2Objects2.length = 0;


return;

}

gdjs['BRIDGECode'] = gdjs.BRIDGECode;
